FROM oven/bun:latest AS builder

WORKDIR /app

COPY . .
RUN bun install

RUN bun build apps/server/index.ts --outfile dist/index.js --target bun

FROM oven/bun:latest
WORKDIR /app

COPY --from=builder /app/dist/index.js ./index.js

EXPOSE 3000

# 启动
CMD ["bun", "index.js"]
