FROM oven/bun:latest AS builder

WORKDIR /app
COPY package.json bun.lock ./
COPY packages/*/package.json ./packages/*/
COPY apps/server/package.json ./apps/server/

COPY packages ./packages
COPY apps/server ./apps/server

RUN bun install


RUN bun build apps/server/index.ts --outfile dist/index.js --target bun

FROM oven/bun:latest
WORKDIR /app

COPY --from=builder /app/dist/index.js ./index.js

EXPOSE 3000

# 启动
CMD ["bun", "index.js"]
